### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by willb335** [willb335/chessboardjsx#15]
The chessboard needs accessibility upgrades.

* Text alternatives and captions for non-text media (pieces)
* Allow users to traverse the board and pick up pieces with only the keyboard

**Comment by P1Wvrs** [comment]
Hello , 
I am integrating Chessboard.jsx which happens to be very smooth and efficient . But I did find some differences between Chessboard.js and Chessboard.jsx functionalities. And how can I implement "OnDragStart" in  Chessboard.jsx ? Will the upcoming versions of Chessboard.jsx have the missing props ? It will be of great help if I get to know when will the updates be available and what are the new features to be added in the next version , so that I can put my code accordingly and think for future scope .
